# Generated by Django 5.0.7 on 2024-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Order Notes'),
        ),
    ]
