# Generated by Django 5.0.7 on 2024-09-27 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_comment_active_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 15, 2, 78738, tzinfo=datetime.timezone.utc), verbose_name='date time created'),
        ),
    ]
